// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzihxHj-d-Gs-hxAvBQxsxS5nHK8v92qA',
    appId: '1:661891819641:web:ca8145bc82519403d90ca8',
    messagingSenderId: '661891819641',
    projectId: 'chat-app-5576c',
    authDomain: 'chat-app-5576c.firebaseapp.com',
    storageBucket: 'chat-app-5576c.firebasestorage.app',
    measurementId: 'G-D42KMNYSGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwePRff40vtNfMyo-4JYk-i6XYg5hIgDg',
    appId: '1:661891819641:android:9dc64deb7f2adca0d90ca8',
    messagingSenderId: '661891819641',
    projectId: 'chat-app-5576c',
    storageBucket: 'chat-app-5576c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHIwC-0oXp_CdzN96ok82siLFAx57gnZY',
    appId: '1:661891819641:ios:ad41cfface9dbe5ed90ca8',
    messagingSenderId: '661891819641',
    projectId: 'chat-app-5576c',
    storageBucket: 'chat-app-5576c.firebasestorage.app',
    iosClientId: '661891819641-ut0t6nptvtuqibl5rnou22acuk7uo55j.apps.googleusercontent.com',
    iosBundleId: 'com.chatApp.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHIwC-0oXp_CdzN96ok82siLFAx57gnZY',
    appId: '1:661891819641:ios:ad41cfface9dbe5ed90ca8',
    messagingSenderId: '661891819641',
    projectId: 'chat-app-5576c',
    storageBucket: 'chat-app-5576c.firebasestorage.app',
    iosClientId: '661891819641-ut0t6nptvtuqibl5rnou22acuk7uo55j.apps.googleusercontent.com',
    iosBundleId: 'com.chatApp.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzihxHj-d-Gs-hxAvBQxsxS5nHK8v92qA',
    appId: '1:661891819641:web:c96669ac0048f24bd90ca8',
    messagingSenderId: '661891819641',
    projectId: 'chat-app-5576c',
    authDomain: 'chat-app-5576c.firebaseapp.com',
    storageBucket: 'chat-app-5576c.firebasestorage.app',
    measurementId: 'G-9E6EY6N8RK',
  );

}